### ISSUE TITLE
Error in Stage 2 of Training

### ISSUE THREAD

**Issue by hononavarro** [DetionDX/Attribute2Sketch2Face#3]
Hi there,
First of all, thank you so much for this repo.
I'm running into this error in the 2nd stage of training using the lfw dataset. Stage 1 runs ok:

---------- Stage2 training -------------
/lib/python2.7/site-packages/torch/nn/functional.py:1444: UserWarning: nn.functional.upsample_nearest is deprecated. Use nn.functional.upsample instead.
  warnings.warn("nn.functional.upsample_nearest is deprecated. Use nn.functional.upsample instead.")
Traceback (most recent call last):
  File "train_lfw.py", line 144, in <module>
    model.optimize_stage2_parameters()
  File "/home/gnm/Attribute2Sketch2Face/models/attr_sketch_face_model.py", line 218, in optimize_stage2_parameters
    self.forward2()
  File "home/gnm/Attribute2Sketch2Face/models/attr_sketch_face_model.py", line 120, in forward2
    self.recon2 = self.netG2.forward(torch.cat([self.recon[0],self.recon[0],self.recon[0]],1), self.enc_text)
  File "home/gnm/Attribute2Sketch2Face/models/asf_networks.py", line 711, in forward
    x9 = self.relu(self.conv_refin(x8))
  File "/lib/python2.7/site-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'Dense' object has no attribute 'relu'

Could you give me some hints about what could be the problem?

Thank you.

**Comment by xingdi1990** [comment]
@hononavarro Thanks for using this code,  I think you can add:
self.relu = nn.ReLU(inplace=True) 
in file "home/gnm/Attribute2Sketch2Face/models/asf_networks.py", line 604
